import { Header } from '~/components';
import '../styles/globals.css';
import PromptInput from '~/components/PromptInput';

export const metadata = {
  title: 'PixelForge AI Image Generator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <PromptInput />

        {children}
      </body>
    </html>
  );
}
