import { Header } from "~/components";
import "../styles/globals.css";

export const metadata = {
  title: "PixelForge AI Image Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* prompt input */}
        {children}
      </body>
    </html>
  );
}
